### ISSUE TITLE
Python: Traceback (most recent call last):

### ISSUE THREAD

**Issue by TemmieDola** [mrven/Blender-Texel-Density-Checker#27]
**Texel_Density_2023_2_Bl400**

I got an error when I try to calculate or set TD to many meshes. I also tryed older version

```
Python: Traceback (most recent call last):
  File "C:\Users\TemmieDola\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Texel_Density_2023_2_Bl400\add_td_operators.py", line 104, in execute
    bpy.ops.object.texel_density_set()
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\TemmieDola\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Texel_Density_2023_2_Bl400\core_td_operators.py", line 299, in execute
    bpy.ops.object.texel_density_check()
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\TemmieDola\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Texel_Density_2023_2_Bl400\core_td_operators.py", line 90, in execute
    local_texel_density += face_td_area_list[face_id][0] * face_td_area_list[face_id][1] / local_area
ZeroDivisionError: float division by zero
Location: C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py:113
Location: C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py:113
```

**Comment by AbdElhalim12** [comment]
same here, did you find any solution?

**Comment by mrven** [comment]
fixed in 2413bdadee0077c5687f58f5cbb3e06510241459
added checks for any selected faced and for dvision by zero
