### ISSUE TITLE
Error: Does not work with the latest version of Blender - 3.0

### ISSUE THREAD

**Issue by Moerti84** [mrven/Blender-Texel-Density-Checker#9]
throws errors with blender 3.0

Python: Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Texel_Density_3_3_291\core_td_operators.py", line 200, in execute
    utils.Sync_UV_Selection()
  File "C:\Users\Moert\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\Texel_Density_3_3_291\utils.py", line 52, in Sync_UV_Selection
    bmesh.update_edit_mesh(mesh, False, False)
TypeError: update_edit_mesh() takes at most 1 positional argument (3 given)

location: <unknown location>:-1

**Comment by Moerti84** [comment]
https://github.com/mrven/Blender-Texel-Density-Checker/blob/ddacbd49dc7cd94dfa0e78d6827220817c4630b3/Texel_Density_3_3_291/utils.py#L52

	bmesh.update_edit_mesh(mesh)
	
	fixed the error.
